import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

import type {
  GenerateModelMapOptions,
  Prisma8ContractJson,
  Prisma8ContractModel,
} from "./types.js";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function ownValue<T>(values: Record<string, T>, key: string): T | undefined {
  return Object.hasOwn(values, key) ? values[key] : undefined;
}

function assertContract(value: unknown): asserts value is Prisma8ContractJson {
  if (!isRecord(value) || !isRecord(value.roots) || !isRecord(value.domain)) {
    throw new Error("The file is not a supported Prisma 8 contract.json.");
  }

  const namespaces = value.domain.namespaces;
  if (!isRecord(namespaces)) {
    throw new Error("The file is not a supported Prisma 8 contract.json.");
  }

  for (const root of Object.values(value.roots)) {
    if (!isRecord(root) || typeof root.model !== "string" || typeof root.namespace !== "string") {
      throw new Error("The file is not a supported Prisma 8 contract.json.");
    }
  }

  for (const namespace of Object.values(namespaces)) {
    if (!isRecord(namespace) || !isRecord(namespace.models)) {
      throw new Error("The file is not a supported Prisma 8 contract.json.");
    }
    for (const model of Object.values(namespace.models)) {
      if (!isRecord(model)) {
        throw new Error("The file is not a supported Prisma 8 contract.json.");
      }
      if (model.relations === undefined) continue;
      if (!isRecord(model.relations)) {
        throw new Error("The file is not a supported Prisma 8 contract.json.");
      }
      for (const relation of Object.values(model.relations)) {
        if (
          !isRecord(relation) ||
          !isRecord(relation.to) ||
          typeof relation.to.model !== "string" ||
          typeof relation.to.namespace !== "string"
        ) {
          throw new Error("The file is not a supported Prisma 8 contract.json.");
        }
      }
    }
  }
}

function relationMap(
  contract: Prisma8ContractJson,
  model: Prisma8ContractModel | undefined,
): Record<string, string> {
  const relations: Record<string, string> = Object.create(null) as Record<string, string>;
  for (const [relationName, relation] of Object.entries(model?.relations ?? {})) {
    const root = Object.entries(contract.roots).find(
      ([, candidate]) =>
        candidate.model === relation.to.model &&
        candidate.namespace === relation.to.namespace,
    );
    if (root) relations[root[0]] = relationName;
  }
  return relations;
}

export function renderModelMap(
  contract: Prisma8ContractJson,
  dbImport: string,
  runtimeImport = "@ejqs/better-auth-prisma8/runtime",
): string {
  const entries = Object.entries(contract.roots)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([rootName, root]) => {
      const namespace = ownValue(contract.domain.namespaces, root.namespace);
      const model = namespace ? ownValue(namespace.models, root.model) : undefined;
      const relations = relationMap(contract, model);
      const relationCode = Object.keys(relations).length
        ? `, relations: ${JSON.stringify(relations)}`
        : "";
      return `    [${JSON.stringify(rootName)}]: { collection: client.orm[${JSON.stringify(root.namespace)}][${JSON.stringify(root.model)}]${relationCode} },`;
    })
    .join("\n");

  return `// Generated by @ejqs/better-auth-prisma8. Do not edit by hand.\nimport { definePrisma8Models } from ${JSON.stringify(runtimeImport)};\nimport { db } from ${JSON.stringify(dbImport)};\n\nexport function createPrisma8Models(client: Pick<typeof db, \"orm\">) {\n  return definePrisma8Models({\n${entries}\n  });\n}\n\nexport const prisma8Models = createPrisma8Models(db);\n`;
}

export async function generateModelMap(options: GenerateModelMapOptions): Promise<string> {
  const parsed: unknown = JSON.parse(await readFile(options.contractPath, "utf8"));
  assertContract(parsed);
  const code = renderModelMap(parsed, options.dbImport, options.runtimeImport);
  await mkdir(dirname(options.outputPath), { recursive: true });
  await writeFile(options.outputPath, code, "utf8");
  return code;
}
