import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

import type {
  GenerateModelMapOptions,
  Prisma8ContractJson,
  Prisma8ContractModel,
} from "./types.js";

function assertContract(value: unknown): asserts value is Prisma8ContractJson {
  if (
    !value ||
    typeof value !== "object" ||
    !("roots" in value) ||
    !("domain" in value)
  ) {
    throw new Error("The file is not a supported Prisma 8 contract.json.");
  }
}

function relationMap(
  contract: Prisma8ContractJson,
  model: Prisma8ContractModel | undefined,
): Record<string, string> {
  const relations: Record<string, string> = {};
  for (const [relationName, relation] of Object.entries(model?.relations ?? {})) {
    const root = Object.entries(contract.roots).find(
      ([, candidate]) =>
        candidate.model === relation.to.model &&
        candidate.namespace === relation.to.namespace,
    );
    if (root) relations[root[0]] = relationName;
  }
  return relations;
}

export function renderModelMap(
  contract: Prisma8ContractJson,
  dbImport: string,
  runtimeImport = "@ejqs/better-auth-prisma8/runtime",
): string {
  const entries = Object.entries(contract.roots)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([rootName, root]) => {
      const model = contract.domain.namespaces[root.namespace]?.models[root.model];
      const relations = relationMap(contract, model);
      const relationCode = Object.keys(relations).length
        ? `, relations: ${JSON.stringify(relations)}`
        : "";
      return `    ${JSON.stringify(rootName)}: { collection: client.orm[${JSON.stringify(root.namespace)}][${JSON.stringify(root.model)}]${relationCode} },`;
    })
    .join("\n");

  return `// Generated by @ejqs/better-auth-prisma8. Do not edit by hand.\nimport { definePrisma8Models } from ${JSON.stringify(runtimeImport)};\nimport { db } from ${JSON.stringify(dbImport)};\n\nexport function createPrisma8Models(client: Pick<typeof db, \"orm\">) {\n  return definePrisma8Models({\n${entries}\n  });\n}\n\nexport const prisma8Models = createPrisma8Models(db);\n`;
}

export async function generateModelMap(options: GenerateModelMapOptions): Promise<string> {
  const parsed: unknown = JSON.parse(await readFile(options.contractPath, "utf8"));
  assertContract(parsed);
  const code = renderModelMap(parsed, options.dbImport, options.runtimeImport);
  await mkdir(dirname(options.outputPath), { recursive: true });
  await writeFile(options.outputPath, code, "utf8");
  return code;
}
